### ISSUE TITLE
Support Parsing "Sheet Music" into Channels

### ISSUE THREAD

**Issue by khalidabuhakmeh** [AutumnSky1010/SoundMaker#3]
👋  こんにちわ!

It would be neat if SoundMaker could parse some "sheet music" format and turn them into wave files.

There's a site called noobnotes that seems to have a user-friendly format. (https://noobnotes.net/super-mario-bros-theme-nintendo/?solfege=false)

Here's a potential use case.

```c#
SoundFormat format = new(FourtyEightKHz, SixteenBit, Monaural);
var rightChannel = new TriangleSoundChannel(100, format, PanType.Right);
var music = 
"""
^E ^E ^E
^C ^E ^G G

 

^C G E
A B Bb A
G ^E ^G ^A
^F ^G ^E ^C ^D B
""";

rightChannel.Process(music);
```

ありがとうございました。

**Comment by AutumnSky1010** [comment]
Thank you for your proposal. I would be happy to do that.

This format is a prototype that was based on your sample.
```text
// Can write comments.
// No distinction between upper and lower case letters. (ex. C4 = c4, rest = Rest)
C4, 4; // or c4
D4#, 2;
E4, 8;
rest, 8;
// ↓Tuplet
{ C4, D4, E4 }, 4; // This is the triplet.
// ↓Tie
C4, { 4, 4, 8 };
rest, 8;
// ↓Tuplet + Tie
{ C4*2, D4 }, 4;  // This is the triplet.
// Tuplet + Tuplet
{ { C4, C4, C4 }, C4, C4 }, 4; // This is the triplet.
// ↓dotted
.C4, 4
rest, 8
```
The sheet music is shown bellow.
![image](https://user-images.githubusercontent.com/66455966/208136960-04d7c1a4-4f70-46db-92d8-6bc56cac1e73.png)

However, there is a problem with it that can be inconvenient because it must be written length of note/rest.
Also, Currently, it is not possible to use dotted notes within a tuplet.( Tuplet class has this problem. )
